ktor:
  application:
    modules:
      - kartverket.no.ApplicationKt.module
  deployment:
    port: 8085

generateRiSc:
  pathRegex: '\.risc\.yaml$'

airTable:
  baseUrl: 'https://api.airtable.com'
  baseId: $AIRTABLE_BASE_ID
  apiToken: $AIRTABLE_API_TOKEN
  tableId: $AIRTABLE_TABLE_ID